language: node_js
node_js:
  - 7

# https://github.com/dwyl/learn-nightwatch/issues/8#issuecomment-264734792
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
script:
  - jdk_switcher use oraclejdk8

cache:
  directories:
    - "node_modules"
