language: node_js
node_js:
  - 12
after_success: 
  - npm run build
deploy:
  - provider: s3
    bucket: mpower.sagebridge.org
    skip_cleanup: true
    acl: public_read
    detect_encoding: false
    region: us-east-1
    local_dir: dist
    on:
      branch: develop
  - provider: s3
    bucket: parkinsonmpower.org
    skip_cleanup: true
    acl: public_read
    detect_encoding: false
    region: us-east-1
    local_dir: dist
    on:
      branch: release
cache:
  directories:
  - node_modules
